curators:
 - LucasRoesler

features:
 - dco_check
 - comments
 - pr_description_required
 - release_notes

required_in_issues:
- "## Why do you need this?"
- "## Expected Behaviour"
- "## Current Behaviour"
- "## List All Possible Solutions and Workarounds"
- "## Steps to Reproduce (for bugs)"
- "## Your Environment"

messages:
  - name: template
    value: |
           Your issue has been marked as *invalid* because you've deleted or removed questions from our issue template.
           
           If you wish to participate in this community, then you need to follow guidelines set by the maintainers.
           
           Edit your issue and use the whole issue template, so that we can help you.

contributing_url: https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md
